services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fitness_app
    ports:
      - '1234:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./server
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/myapp?schema=public'
      DB_HOST: 'postgres'
      JWT_SECRET: 'your-secret-key'
    depends_on:
      - postgres

  app:
    build: ./client
    ports:
      - '80:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000

volumes:
  postgres_data:
